### ISSUE TITLE
java.lang.NullPointerException in super.onCreate(savedInstanceState);

### ISSUE THREAD

**Issue by manufuentescr** [VuframeLab/PanicAR-android#5]
I tried the demo and it works perfectly.

I try to recreate the demo on a new project but I get an error PanicARFragment

This is the log:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{pruebaar.example.com.pruebaar/pruebaar.example.com.pruebaar.ARPortraitActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
            at android.app.ActivityThread.access$600(ActivityThread.java:153)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at com.dopanic.panicsensorkit.PSKSensorManager.<init>(PSKSensorManager.java:62)
            at com.dopanic.panicsensorkit.PSKSensorManager.getSharedSensorManager(PSKSensorManager.java:205)
            at com.dopanic.panicarkit.lib.PARFragment.onCreate(PARFragment.java:121)
            at pruebaar.example.com.pruebaar.PanicARFragment.onCreate(PanicARFragment.java:41)
            at android.app.Fragment.performCreate(Fragment.java:1673)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:854)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
            at android.app.BackStackRecord.run(BackStackRecord.java:682)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
            at android.app.Activity.performStart(Activity.java:5142)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
            at android.app.ActivityThread.access$600(ActivityThread.java:153)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
            at dalvik.system.NativeStart.main(Native Method)
```

what am I doing wrong ?

**Comment by tsakmalis** [comment]
I have the same problem! Did you find anything?

**Comment by Onkarn92** [comment]
Same Problem! Please suggest solution...

**Comment by umeryounus1994** [comment]
Anyone found the solution for this?

**Comment by Onkarn92** [comment]
@UmerYounus Post your custom application class.
